language: node_js
node_js:
  - "8"

install:
  - npm install -g typescript
  - npm install

before_script:
  - node -v
  - npm -v
  - tsc -v

stages:
  - test
  - build

jobs:
  include:
    - stage: test
      script: npm run lint && npm run prettier:check && npm run report
    - stage: build
      script: npm run build